services:
  clip-of-the-day:
    image: clip-of-the-day
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - VIDEO_DIRECTORY=/Captures/
    volumes:
      - type: bind
        source: ${VIDEO_DIRECTORY}
        target: /Captures/
    build:
      context: .
      dockerfile: dockerfile
      labels:
        - "clip-of-the-day"
