FROM python:3.10.12

WORKDIR /file-watcher
COPY ./file_watcher ./file_watcher
COPY ./common ./common
RUN pip install --upgrade pip
RUN pip install -r ./file_watcher/requirements.txt
CMD [ "python", "-u", "-m", "file_watcher.file_watcher"]