FROM python:3.10.0-alpine

WORKDIR /file-watcher
COPY ./file_watcher ./config.py ./app/db_models.py ./requirements.txt ./
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
CMD [ "python", "-u", "-m", "file_watcher.file_watcher"]